In [1]:
print("data analysis using numpy")

data analysis using numpy


In [6]:
import numpy as np
import time



0.03778696060180664


In [12]:
#using python list
size=1_000_000
l1=list(range(size))
l2=list(range(size))

start=time.time()

add=[x+y for x,y in zip(l1,l2)]
end=time.time()
print(add[0:10])
print(end-start)


[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
0.038027048110961914


In [13]:
# using numpy array
size=1_000_000
l1=np.array(list(range(size)))
l2=np.array(list(range(size)))

start=time.time()
add=l1+l2
end=time.time()
print(add[0:10])

print(end-start)


[ 0  2  4  6  8 10 12 14 16 18]
0.013579130172729492


In [15]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [16]:
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [17]:
type(arr)

numpy.ndarray

In [18]:
print(type(arr))

<class 'numpy.ndarray'>


In [19]:
arr.shape

(2, 5)

In [23]:
import sys
list_data=list(range(1000))
numpy_data=np.array(list_data)
print('python list size', sys.getsizeof(list_data)*len(list_data), 'bytes')
print('numpy array size:', numpy_data.nbytes, 'bytes')

python list size 8056000 bytes
numpy array size: 8000 bytes


In [27]:
l5=list(range(100000))

start=time.time()
list_squares=[i**2 for i in l5]
end=time.time()
print(end-start)

0.01321721076965332


In [28]:
l6=np.arange(100000)

start=time.time()
l6**2
end=time.time()
print(end-start)

0.0011489391326904297


In [1]:
myarr= np.array([[1,2,3], [4,5,6],[9,10,22]])

NameError: name 'np' is not defined