In [1]:
import numpy as np
import scipy.stats as stats

In [5]:
observed_data=np.array([[50,30,20],
                      [30,40,30],
                      [20,30,50]])

#perform the chi square test

chi2_stats_value,p_value,df,expected=stats.chi2_contingency(observed_data)

print(chi2_stats_value)
print(p_value)
print(df)
print(expected)

30.0
4.894437128029217e-06
4
[[33.33333333 33.33333333 33.33333333]
 [33.33333333 33.33333333 33.33333333]
 [33.33333333 33.33333333 33.33333333]]


In [8]:
alpha=0.05
if(p_value<alpha):
    print('reject the null hypothesis')
else:
    print('failed to reject the hypothesis')

failed to reject the hypothesis
